{% set name = "xrpl-py" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/XRPLF/xrpl-py/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 4caa646cf5aa8a618d74c545ad600b158d6f627bfa3bf7ffa861021fdc5e25ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - poetry
    - python {{ python_min }}
    - pip
  run:
    - base58 >=2.1.0,<3
    - ECPy >=1.2.5,<2
    - httpx >=0.18.1,<0.25.0
    - websockets >=11.0,<12
    - deprecated >=1.2.13,<2
    - types-Deprecated >=1.2.9,<2
    - pycryptodome >=3.16.0,<4
    - python >={{ python_min }}
    - typing-extensions >=4.2.0,<5

test:
  imports:
    - xrpl
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests
  commands:
    - pip check
    - pytest tests/unit

about:
  home: https://github.com/XRPLF/xrpl-py
  summary: 'A pure Python implementation for interacting with the XRP Ledger.'
  description: |
    The xrpl-py library simplifies the hardest parts of XRP Ledger interaction, like serialization
    and transaction signing. It also provides native Python methods and models for XRP Ledger
    transactions and core server API (rippled) objects.
  license: ISC
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MementoRC
